### ISSUE TITLE
Bug - query, fetch and get not returning promise if rejected

### ISSUE THREAD

**Issue by dani3l** [VasilioRuzanni/angular-modelizer#5]
Hi dude

take a look at lines: 1790, 2175, 2609, 2643
https://github.com/VasilioRuzanni/angular-modelizer/blob/master/dist/angular-modelizer.js#L1790

You fire $q.reject but you never return it so you can't catch the promise
discovered this when route got resolved even when server returned an error

**Comment by VasilioRuzanni** [comment]
@dani3l Thanks for the catch! Will take a look. Thanks!

**Comment by VasilioRuzanni** [comment]
@dani3l Fixed, feel free to reopen or create another one if there are any related issues.

**Comment by dani3l** [comment]
cool. thanks :)
